### ISSUE TITLE
华为已经有CLI工具了，可以结合CLI工具进行动态更新DNS

### ISSUE THREAD

**Issue by derekhe** [lllvcs/huaweicloud_ddns#3]
https://support.huaweicloud.com/qs-hcli/hcli_02_003.html

**Comment by lllvcs** [comment]
本shell主要考虑是精简性和普适性。
而您说的这个CLI工具文件过大，在低性能设备（家用路由器）上难以存储、运行，没有很大的参考价值和意义。
谢谢。
