### ISSUE TITLE
华为 云DNS解析添加  双栈出现 V6更新正常  V4不能更新

### ISSUE THREAD

**Issue by ghost** [lllvcs/huaweicloud_ddns#4]
![NJOS`JNE029%YA_}@HA~I7R](https://user-images.githubusercontent.com/80835623/129002783-b1a6780a-d8da-485b-85c2-c7ac9dbd0f8c.png)
本来用的V4脚本一直正常 后来为了访问80端口我就 用大佬的V6解析脚本   解析V6也是正常解析 但是后来发现启用双栈后 导致v4就不能正常解析了运行V4脚本出错 ， 如果删除AAAA记录 V4就能正常解析 不删除AAAA记录 双栈就出现下面是更新V4的错误代码
{"code":"DNS.0308","message":"Attribute 'records' is invalid. When type is 'AAAA', records should be ipv6 address list."}

![X@`LSI3_7Q XLO1_AE~%H6F](https://user-images.githubusercontent.com/80835623/129001705-a96302c6-f8d8-461f-82c2-948943336f2c.png)

**Comment by lllvcs** [comment]
请自主获取各个记录的 ZONE_ID 和 RECORDSET_ID，并使用最新版本的脚本

**Comment by miss85246** [comment]
请问什么是 ZONE_ID 和 RECORDSET_ID, 华为云上没有标明啊

**Comment by lllvcs** [comment]
> 请问什么是 ZONE_ID 和 RECORDSET_ID, 华为云上没有标明啊

建议咨询华为云客服专员，谢谢！
